# Generated by Django 5.1.7 on 2026-02-17 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_add_gateway_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeweb_server_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('ssh_user', models.CharField(default='root', max_length=50)),
                ('ssh_password', models.CharField(blank=True, max_length=255)),
                ('ssh_port', models.IntegerField(default=22)),
                ('status', models.CharField(choices=[('creating', 'Создается'), ('provisioning', 'Настраивается'), ('active', 'Активен'), ('error', 'Ошибка'), ('deactivated', 'Деактивирован')], default='creating', max_length=20)),
                ('openclaw_running', models.BooleanField(default=False)),
                ('openclaw_path', models.CharField(default='/root/openclaw', max_length=255)),
                ('clawdmatrix_installed', models.BooleanField(default=False)),
                ('gateway_token', models.CharField(blank=True, max_length=255)),
                ('last_error', models.TextField(blank=True)),
                ('last_health_check', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='server', to='accounts.userprofile')),
            ],
            options={
                'verbose_name': 'Сервер',
                'verbose_name_plural': 'Серверы',
            },
        ),
    ]
