# Generated by Django 5.1.5 on 2026-02-12 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Лог',
                'verbose_name_plural': 'Логи',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('avatar_url', models.URLField(blank=True)),
                ('telegram_bot_token', models.CharField(blank=True, max_length=255)),
                ('telegram_bot_username', models.CharField(blank=True, max_length=255)),
                ('telegram_bot_validated', models.BooleanField(default=False)),
                ('selected_model', models.CharField(choices=[('claude-sonnet-4', 'Claude Sonnet 4'), ('claude-opus-4.5', 'Claude Opus 4.5'), ('claude-haiku-4.5', 'Claude Haiku 4.5'), ('gemini-3-flash', 'Gemini 3 Flash'), ('gemini-2.5-flash', 'Gemini 2.5 Flash')], default='claude-sonnet-4', max_length=50)),
                ('subscription_status', models.CharField(choices=[('none', 'Нет подписки'), ('pending', 'Ожидание оплаты'), ('active', 'Активна'), ('cancelled', 'Отменена'), ('expired', 'Истекла')], default='none', max_length=20)),
                ('subscription_started_at', models.DateTimeField(blank=True, null=True)),
                ('subscription_expires_at', models.DateTimeField(blank=True, null=True)),
                ('openrouter_api_key', models.CharField(blank=True, max_length=255)),
                ('openrouter_key_id', models.CharField(blank=True, max_length=255)),
                ('tokens_used_usd', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('token_limit_usd', models.DecimalField(decimal_places=2, default=15.0, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
    ]
