# Generated by Django 5.1.5 on 2026-02-12 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_change_default_model_to_sonnet'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='apple_id',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
    ]
