# Generated by Django 5.1.7 on 2026-02-17 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_apple_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='clawdmatrix_custom_skills',
            field=models.JSONField(blank=True, default=dict, help_text='Per-user skill overrides (merged with defaults)', verbose_name='Custom ClawdMatrix Skills'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='clawdmatrix_enabled',
            field=models.BooleanField(default=False, verbose_name='ClawdMatrix Engine'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='selected_model',
            field=models.CharField(choices=[('gemini-3-flash-preview', 'Gemini 3 Flash Preview'), ('claude-opus-4', 'Claude Opus 4'), ('gpt-5.2', 'GPT 5.2')], default='gemini-3-flash-preview', max_length=50),
        ),
    ]
