# Generated by Django 5.1.5 on 2026-02-18 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_gateway_token'),
        ('accounts', '0003_userprofile_clawdmatrix_custom_skills_and_more'),
    ]

    operations = [
    ]
